name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        REACT_APP_FIREBASE_API_KEY: "AIzaSyDwCj5Q0mrXUkDyR42JXKoldsQZB3ay1bc"
        REACT_APP_FIREBASE_AUTH_DOMAIN: "lockmanblog.firebaseapp.com"
        REACT_APP_FIREBASE_PROJECT_ID: "lockmanblog"
        REACT_APP_FIREBASE_STORAGE_BUCKET: "lockmanblog.firebasestorage.app"
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "269919632510"
        REACT_APP_FIREBASE_APP_ID: "1:269919632510:web:b16aaf65d182266c676c2f"
        REACT_APP_FIREBASE_MEASUREMENT_ID: "G-347BJ7MDYQ"
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
